// Code generated by protoc-gen-go. DO NOT EDIT.
// source: couler.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Parameter struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value can be used in templates and steps
	// in templates: value is how the parameter can be referred to
	// in steps: actual value to be passed to the step
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	GlobalName           string   `protobuf:"bytes,3,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{0}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Parameter) GetGlobalName() string {
	if m != nil {
		return m.GlobalName
	}
	return ""
}

type Secret struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{1}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Secret) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Secret) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Artifact struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value can be only used steps as the "from" field:
	// https://argoproj.github.io/argo/examples/#artifacts
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	LocalPath            string   `protobuf:"bytes,4,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath           string   `protobuf:"bytes,5,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	AccessKey            *Secret  `protobuf:"bytes,6,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey            *Secret  `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Endpoint             string   `protobuf:"bytes,8,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Bucket               string   `protobuf:"bytes,9,opt,name=bucket,proto3" json:"bucket,omitempty"`
	GlobalName           string   `protobuf:"bytes,10,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Artifact) Reset()         { *m = Artifact{} }
func (m *Artifact) String() string { return proto.CompactTextString(m) }
func (*Artifact) ProtoMessage()    {}
func (*Artifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{2}
}

func (m *Artifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artifact.Unmarshal(m, b)
}
func (m *Artifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artifact.Marshal(b, m, deterministic)
}
func (m *Artifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artifact.Merge(m, src)
}
func (m *Artifact) XXX_Size() int {
	return xxx_messageInfo_Artifact.Size(m)
}
func (m *Artifact) XXX_DiscardUnknown() {
	xxx_messageInfo_Artifact.DiscardUnknown(m)
}

var xxx_messageInfo_Artifact proto.InternalMessageInfo

func (m *Artifact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Artifact) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Artifact) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Artifact) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

func (m *Artifact) GetRemotePath() string {
	if m != nil {
		return m.RemotePath
	}
	return ""
}

func (m *Artifact) GetAccessKey() *Secret {
	if m != nil {
		return m.AccessKey
	}
	return nil
}

func (m *Artifact) GetSecretKey() *Secret {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

func (m *Artifact) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Artifact) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *Artifact) GetGlobalName() string {
	if m != nil {
		return m.GlobalName
	}
	return ""
}

type StdOut struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StdOut) Reset()         { *m = StdOut{} }
func (m *StdOut) String() string { return proto.CompactTextString(m) }
func (*StdOut) ProtoMessage()    {}
func (*StdOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{3}
}

func (m *StdOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StdOut.Unmarshal(m, b)
}
func (m *StdOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StdOut.Marshal(b, m, deterministic)
}
func (m *StdOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StdOut.Merge(m, src)
}
func (m *StdOut) XXX_Size() int {
	return xxx_messageInfo_StdOut.Size(m)
}
func (m *StdOut) XXX_DiscardUnknown() {
	xxx_messageInfo_StdOut.DiscardUnknown(m)
}

var xxx_messageInfo_StdOut proto.InternalMessageInfo

func (m *StdOut) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StepIO struct {
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source int32  `protobuf:"varint,2,opt,name=source,proto3" json:"source,omitempty"`
	// Types that are valid to be assigned to StepIo:
	//	*StepIO_Parameter
	//	*StepIO_Artifact
	//	*StepIO_Stdout
	StepIo               isStepIO_StepIo `protobuf_oneof:"step_io"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StepIO) Reset()         { *m = StepIO{} }
func (m *StepIO) String() string { return proto.CompactTextString(m) }
func (*StepIO) ProtoMessage()    {}
func (*StepIO) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{4}
}

func (m *StepIO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepIO.Unmarshal(m, b)
}
func (m *StepIO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepIO.Marshal(b, m, deterministic)
}
func (m *StepIO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepIO.Merge(m, src)
}
func (m *StepIO) XXX_Size() int {
	return xxx_messageInfo_StepIO.Size(m)
}
func (m *StepIO) XXX_DiscardUnknown() {
	xxx_messageInfo_StepIO.DiscardUnknown(m)
}

var xxx_messageInfo_StepIO proto.InternalMessageInfo

func (m *StepIO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StepIO) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

type isStepIO_StepIo interface {
	isStepIO_StepIo()
}

type StepIO_Parameter struct {
	Parameter *Parameter `protobuf:"bytes,3,opt,name=parameter,proto3,oneof"`
}

type StepIO_Artifact struct {
	Artifact *Artifact `protobuf:"bytes,4,opt,name=artifact,proto3,oneof"`
}

type StepIO_Stdout struct {
	Stdout *StdOut `protobuf:"bytes,5,opt,name=stdout,proto3,oneof"`
}

func (*StepIO_Parameter) isStepIO_StepIo() {}

func (*StepIO_Artifact) isStepIO_StepIo() {}

func (*StepIO_Stdout) isStepIO_StepIo() {}

func (m *StepIO) GetStepIo() isStepIO_StepIo {
	if m != nil {
		return m.StepIo
	}
	return nil
}

func (m *StepIO) GetParameter() *Parameter {
	if x, ok := m.GetStepIo().(*StepIO_Parameter); ok {
		return x.Parameter
	}
	return nil
}

func (m *StepIO) GetArtifact() *Artifact {
	if x, ok := m.GetStepIo().(*StepIO_Artifact); ok {
		return x.Artifact
	}
	return nil
}

func (m *StepIO) GetStdout() *StdOut {
	if x, ok := m.GetStepIo().(*StepIO_Stdout); ok {
		return x.Stdout
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StepIO) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StepIO_Parameter)(nil),
		(*StepIO_Artifact)(nil),
		(*StepIO_Stdout)(nil),
	}
}

type VolumeMount struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeMount) Reset()         { *m = VolumeMount{} }
func (m *VolumeMount) String() string { return proto.CompactTextString(m) }
func (*VolumeMount) ProtoMessage()    {}
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{5}
}

func (m *VolumeMount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeMount.Unmarshal(m, b)
}
func (m *VolumeMount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeMount.Marshal(b, m, deterministic)
}
func (m *VolumeMount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeMount.Merge(m, src)
}
func (m *VolumeMount) XXX_Size() int {
	return xxx_messageInfo_VolumeMount.Size(m)
}
func (m *VolumeMount) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeMount.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeMount proto.InternalMessageInfo

func (m *VolumeMount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VolumeMount) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// This is only a placeholder and currently only emptyDir volume source is supported.
type VolumeSource struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeSource) Reset()         { *m = VolumeSource{} }
func (m *VolumeSource) String() string { return proto.CompactTextString(m) }
func (*VolumeSource) ProtoMessage()    {}
func (*VolumeSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{6}
}

func (m *VolumeSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSource.Unmarshal(m, b)
}
func (m *VolumeSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSource.Marshal(b, m, deterministic)
}
func (m *VolumeSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSource.Merge(m, src)
}
func (m *VolumeSource) XXX_Size() int {
	return xxx_messageInfo_VolumeSource.Size(m)
}
func (m *VolumeSource) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSource.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSource proto.InternalMessageInfo

func (m *VolumeSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Volume struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source               *VolumeSource `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{7}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetSource() *VolumeSource {
	if m != nil {
		return m.Source
	}
	return nil
}

type ContainerSpec struct {
	Image                string            `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command              []string          `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env                  map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources            map[string]string `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	VolumeMounts         []*VolumeMount    `protobuf:"bytes,7,rep,name=volume_mounts,json=volumeMounts,proto3" json:"volume_mounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContainerSpec) Reset()         { *m = ContainerSpec{} }
func (m *ContainerSpec) String() string { return proto.CompactTextString(m) }
func (*ContainerSpec) ProtoMessage()    {}
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{8}
}

func (m *ContainerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerSpec.Unmarshal(m, b)
}
func (m *ContainerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerSpec.Marshal(b, m, deterministic)
}
func (m *ContainerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerSpec.Merge(m, src)
}
func (m *ContainerSpec) XXX_Size() int {
	return xxx_messageInfo_ContainerSpec.Size(m)
}
func (m *ContainerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerSpec proto.InternalMessageInfo

func (m *ContainerSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ContainerSpec) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ContainerSpec) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ContainerSpec) GetResources() map[string]string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ContainerSpec) GetVolumeMounts() []*VolumeMount {
	if m != nil {
		return m.VolumeMounts
	}
	return nil
}

type ResourceSpec struct {
	Manifest             string   `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	SuccessCondition     string   `protobuf:"bytes,2,opt,name=success_condition,json=successCondition,proto3" json:"success_condition,omitempty"`
	FailureCondition     string   `protobuf:"bytes,3,opt,name=failure_condition,json=failureCondition,proto3" json:"failure_condition,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	SetOwnerReference    bool     `protobuf:"varint,5,opt,name=set_owner_reference,json=setOwnerReference,proto3" json:"set_owner_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceSpec) Reset()         { *m = ResourceSpec{} }
func (m *ResourceSpec) String() string { return proto.CompactTextString(m) }
func (*ResourceSpec) ProtoMessage()    {}
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{9}
}

func (m *ResourceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceSpec.Unmarshal(m, b)
}
func (m *ResourceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceSpec.Marshal(b, m, deterministic)
}
func (m *ResourceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceSpec.Merge(m, src)
}
func (m *ResourceSpec) XXX_Size() int {
	return xxx_messageInfo_ResourceSpec.Size(m)
}
func (m *ResourceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceSpec proto.InternalMessageInfo

func (m *ResourceSpec) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *ResourceSpec) GetSuccessCondition() string {
	if m != nil {
		return m.SuccessCondition
	}
	return ""
}

func (m *ResourceSpec) GetFailureCondition() string {
	if m != nil {
		return m.FailureCondition
	}
	return ""
}

func (m *ResourceSpec) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ResourceSpec) GetSetOwnerReference() bool {
	if m != nil {
		return m.SetOwnerReference
	}
	return false
}

type CannedStepSpec struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 map[string]string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Inputs               []*StepIO         `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*StepIO         `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CannedStepSpec) Reset()         { *m = CannedStepSpec{} }
func (m *CannedStepSpec) String() string { return proto.CompactTextString(m) }
func (*CannedStepSpec) ProtoMessage()    {}
func (*CannedStepSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{10}
}

func (m *CannedStepSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CannedStepSpec.Unmarshal(m, b)
}
func (m *CannedStepSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CannedStepSpec.Marshal(b, m, deterministic)
}
func (m *CannedStepSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CannedStepSpec.Merge(m, src)
}
func (m *CannedStepSpec) XXX_Size() int {
	return xxx_messageInfo_CannedStepSpec.Size(m)
}
func (m *CannedStepSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CannedStepSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CannedStepSpec proto.InternalMessageInfo

func (m *CannedStepSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CannedStepSpec) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CannedStepSpec) GetInputs() []*StepIO {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *CannedStepSpec) GetOutputs() []*StepIO {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Step struct {
	Id                   int32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TmplName             string              `protobuf:"bytes,3,opt,name=tmpl_name,json=tmplName,proto3" json:"tmpl_name,omitempty"`
	ContainerSpec        *ContainerSpec      `protobuf:"bytes,4,opt,name=container_spec,json=containerSpec,proto3" json:"container_spec,omitempty"`
	ResourceSpec         *ResourceSpec       `protobuf:"bytes,5,opt,name=resource_spec,json=resourceSpec,proto3" json:"resource_spec,omitempty"`
	CannedStepSpec       *CannedStepSpec     `protobuf:"bytes,6,opt,name=canned_step_spec,json=cannedStepSpec,proto3" json:"canned_step_spec,omitempty"`
	Script               string              `protobuf:"bytes,7,opt,name=script,proto3" json:"script,omitempty"`
	Args                 []*StepIO           `protobuf:"bytes,8,rep,name=args,proto3" json:"args,omitempty"`
	Dependencies         []string            `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	When                 string              `protobuf:"bytes,10,opt,name=when,proto3" json:"when,omitempty"`
	Attrs                map[string]*any.Any `protobuf:"bytes,11,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Secrets              []*Secret           `protobuf:"bytes,12,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Volumes              []*Volume           `protobuf:"bytes,13,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{11}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetTmplName() string {
	if m != nil {
		return m.TmplName
	}
	return ""
}

func (m *Step) GetContainerSpec() *ContainerSpec {
	if m != nil {
		return m.ContainerSpec
	}
	return nil
}

func (m *Step) GetResourceSpec() *ResourceSpec {
	if m != nil {
		return m.ResourceSpec
	}
	return nil
}

func (m *Step) GetCannedStepSpec() *CannedStepSpec {
	if m != nil {
		return m.CannedStepSpec
	}
	return nil
}

func (m *Step) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *Step) GetArgs() []*StepIO {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Step) GetDependencies() []string {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Step) GetWhen() string {
	if m != nil {
		return m.When
	}
	return ""
}

func (m *Step) GetAttrs() map[string]*any.Any {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Step) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *Step) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type ConcurrentSteps struct {
	Steps                []*Step  `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConcurrentSteps) Reset()         { *m = ConcurrentSteps{} }
func (m *ConcurrentSteps) String() string { return proto.CompactTextString(m) }
func (*ConcurrentSteps) ProtoMessage()    {}
func (*ConcurrentSteps) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{12}
}

func (m *ConcurrentSteps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConcurrentSteps.Unmarshal(m, b)
}
func (m *ConcurrentSteps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConcurrentSteps.Marshal(b, m, deterministic)
}
func (m *ConcurrentSteps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConcurrentSteps.Merge(m, src)
}
func (m *ConcurrentSteps) XXX_Size() int {
	return xxx_messageInfo_ConcurrentSteps.Size(m)
}
func (m *ConcurrentSteps) XXX_DiscardUnknown() {
	xxx_messageInfo_ConcurrentSteps.DiscardUnknown(m)
}

var xxx_messageInfo_ConcurrentSteps proto.InternalMessageInfo

func (m *ConcurrentSteps) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type StepTemplate struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inputs               []*StepIO `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*StepIO `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StepTemplate) Reset()         { *m = StepTemplate{} }
func (m *StepTemplate) String() string { return proto.CompactTextString(m) }
func (*StepTemplate) ProtoMessage()    {}
func (*StepTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{13}
}

func (m *StepTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepTemplate.Unmarshal(m, b)
}
func (m *StepTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepTemplate.Marshal(b, m, deterministic)
}
func (m *StepTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepTemplate.Merge(m, src)
}
func (m *StepTemplate) XXX_Size() int {
	return xxx_messageInfo_StepTemplate.Size(m)
}
func (m *StepTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_StepTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_StepTemplate proto.InternalMessageInfo

func (m *StepTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StepTemplate) GetInputs() []*StepIO {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *StepTemplate) GetOutputs() []*StepIO {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Workflow struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// sequential steps: [ [step], [step], [step], ...]
	// concurrent steps: [ [step], [step, step, step], ...]
	// if dependencies was set, no matter what structure the
	// "steps" field stores, generate a DAG.
	Steps                []*ConcurrentSteps       `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Templates            map[string]*StepTemplate `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Parallelism          int32                    `protobuf:"varint,4,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	Secret               string                   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	ExitHandlerSteps     []*Step                  `protobuf:"bytes,6,rep,name=exit_handler_steps,json=exitHandlerSteps,proto3" json:"exit_handler_steps,omitempty"`
	Attrs                map[string]*any.Any      `protobuf:"bytes,7,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Workflow) Reset()         { *m = Workflow{} }
func (m *Workflow) String() string { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()    {}
func (*Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc28e41c19c684e1, []int{14}
}

func (m *Workflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow.Unmarshal(m, b)
}
func (m *Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow.Marshal(b, m, deterministic)
}
func (m *Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow.Merge(m, src)
}
func (m *Workflow) XXX_Size() int {
	return xxx_messageInfo_Workflow.Size(m)
}
func (m *Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow proto.InternalMessageInfo

func (m *Workflow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Workflow) GetSteps() []*ConcurrentSteps {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Workflow) GetTemplates() map[string]*StepTemplate {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *Workflow) GetParallelism() int32 {
	if m != nil {
		return m.Parallelism
	}
	return 0
}

func (m *Workflow) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Workflow) GetExitHandlerSteps() []*Step {
	if m != nil {
		return m.ExitHandlerSteps
	}
	return nil
}

func (m *Workflow) GetAttrs() map[string]*any.Any {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameter)(nil), "couler.v1.Parameter")
	proto.RegisterType((*Secret)(nil), "couler.v1.Secret")
	proto.RegisterType((*Artifact)(nil), "couler.v1.Artifact")
	proto.RegisterType((*StdOut)(nil), "couler.v1.StdOut")
	proto.RegisterType((*StepIO)(nil), "couler.v1.StepIO")
	proto.RegisterType((*VolumeMount)(nil), "couler.v1.VolumeMount")
	proto.RegisterType((*VolumeSource)(nil), "couler.v1.VolumeSource")
	proto.RegisterType((*Volume)(nil), "couler.v1.Volume")
	proto.RegisterType((*ContainerSpec)(nil), "couler.v1.ContainerSpec")
	proto.RegisterMapType((map[string]string)(nil), "couler.v1.ContainerSpec.EnvEntry")
	proto.RegisterMapType((map[string]string)(nil), "couler.v1.ContainerSpec.ResourcesEntry")
	proto.RegisterType((*ResourceSpec)(nil), "couler.v1.ResourceSpec")
	proto.RegisterType((*CannedStepSpec)(nil), "couler.v1.CannedStepSpec")
	proto.RegisterMapType((map[string]string)(nil), "couler.v1.CannedStepSpec.ArgsEntry")
	proto.RegisterType((*Step)(nil), "couler.v1.Step")
	proto.RegisterMapType((map[string]*any.Any)(nil), "couler.v1.Step.AttrsEntry")
	proto.RegisterType((*ConcurrentSteps)(nil), "couler.v1.ConcurrentSteps")
	proto.RegisterType((*StepTemplate)(nil), "couler.v1.StepTemplate")
	proto.RegisterType((*Workflow)(nil), "couler.v1.Workflow")
	proto.RegisterMapType((map[string]*any.Any)(nil), "couler.v1.Workflow.AttrsEntry")
	proto.RegisterMapType((map[string]*StepTemplate)(nil), "couler.v1.Workflow.TemplatesEntry")
}

func init() { proto.RegisterFile("couler.proto", fileDescriptor_dc28e41c19c684e1) }

var fileDescriptor_dc28e41c19c684e1 = []byte{
	// 1165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0x8e, 0xbf, 0x36, 0xde, 0x63, 0xc7, 0x4d, 0xa6, 0x55, 0xba, 0xf5, 0xfb, 0x02, 0x61, 0x51,
	0x45, 0x20, 0xc2, 0x49, 0xdc, 0x42, 0x2b, 0x28, 0x82, 0x34, 0x44, 0x0a, 0x42, 0x6d, 0xaa, 0x0d,
	0x14, 0x89, 0x1b, 0x6b, 0xb2, 0x1e, 0x3b, 0xab, 0xec, 0xce, 0xae, 0x66, 0x66, 0x1d, 0xcc, 0xbf,
	0xe3, 0x9e, 0x5b, 0x6e, 0xb9, 0xe6, 0xaa, 0xbf, 0x01, 0xcd, 0x97, 0xbd, 0xb6, 0xd7, 0x42, 0x91,
	0xb8, 0xdb, 0x33, 0xf3, 0x9c, 0x33, 0xe7, 0xe3, 0x39, 0xe7, 0x2c, 0xb4, 0xc3, 0x34, 0x8f, 0x09,
	0xeb, 0x65, 0x2c, 0x15, 0x29, 0x72, 0x8d, 0x34, 0x39, 0xee, 0x3e, 0x1a, 0xa7, 0xe9, 0x38, 0x26,
	0x87, 0xea, 0xe2, 0x2a, 0x1f, 0x1d, 0x62, 0x3a, 0xd5, 0x28, 0xff, 0x2d, 0xb8, 0x6f, 0x30, 0xc3,
	0x09, 0x11, 0x84, 0x21, 0x04, 0x75, 0x8a, 0x13, 0xe2, 0x55, 0xf6, 0x2a, 0xfb, 0x6e, 0xa0, 0xbe,
	0xd1, 0x03, 0x68, 0x4c, 0x70, 0x9c, 0x13, 0xaf, 0xaa, 0x0e, 0xb5, 0x80, 0x3e, 0x80, 0xd6, 0x38,
	0x4e, 0xaf, 0x70, 0x3c, 0x50, 0x0a, 0x35, 0x75, 0x07, 0xfa, 0xe8, 0x35, 0x4e, 0x88, 0xff, 0x1d,
	0x38, 0x97, 0x24, 0x64, 0x44, 0x94, 0x1a, 0xdd, 0x86, 0xda, 0x0d, 0x99, 0x1a, 0x93, 0xf2, 0x73,
	0xfe, 0x4c, 0xad, 0xf0, 0x8c, 0xff, 0x7b, 0x15, 0x9a, 0x27, 0x4c, 0x44, 0x23, 0x1c, 0x8a, 0x3b,
	0x78, 0x87, 0xa0, 0x2e, 0xa6, 0x99, 0xb5, 0xa5, 0xbe, 0xd1, 0x7b, 0x00, 0x71, 0x1a, 0xe2, 0x78,
	0x90, 0x61, 0x71, 0xed, 0xd5, 0xd5, 0x8d, 0xab, 0x4e, 0xde, 0x60, 0x71, 0x2d, 0x03, 0x62, 0x24,
	0x49, 0x05, 0xd1, 0xf7, 0x0d, 0x1d, 0x90, 0x3e, 0x52, 0x80, 0x23, 0x00, 0x1c, 0x86, 0x84, 0xf3,
	0x81, 0xf4, 0xdc, 0xd9, 0xab, 0xec, 0xb7, 0xfa, 0x3b, 0xbd, 0x59, 0x8e, 0x7b, 0x3a, 0xda, 0xc0,
	0xd5, 0xa0, 0x1f, 0xc8, 0x54, 0x6a, 0x70, 0x75, 0xa8, 0x34, 0x36, 0xd7, 0x6a, 0x68, 0x90, 0xd4,
	0xe8, 0x42, 0x93, 0xd0, 0x61, 0x96, 0x46, 0x54, 0x78, 0x4d, 0xe5, 0xc1, 0x4c, 0x46, 0xbb, 0xe0,
	0x5c, 0xe5, 0xe1, 0x0d, 0x11, 0x9e, 0xab, 0x6e, 0x8c, 0xb4, 0x5c, 0x09, 0x58, 0xa9, 0xc4, 0xff,
	0xc1, 0xb9, 0x14, 0xc3, 0x8b, 0xbc, 0x34, 0x81, 0xfe, 0x9f, 0x15, 0x79, 0x4d, 0xb2, 0xef, 0x2f,
	0x4a, 0xf3, 0xbb, 0x0b, 0x0e, 0x4f, 0x73, 0x16, 0xea, 0x04, 0x37, 0x02, 0x23, 0xa1, 0xa7, 0xe0,
	0x66, 0x96, 0x36, 0x2a, 0xcd, 0xad, 0xfe, 0x83, 0x42, 0x68, 0x33, 0x4a, 0x9d, 0x6f, 0x04, 0x73,
	0x20, 0x3a, 0x86, 0x26, 0x36, 0xd5, 0x54, 0x15, 0x68, 0xf5, 0xef, 0x17, 0x94, 0x6c, 0xa1, 0xcf,
	0x37, 0x82, 0x19, 0x0c, 0x1d, 0x80, 0xc3, 0xc5, 0x30, 0xcd, 0x85, 0x2a, 0xc9, 0x52, 0x02, 0x55,
	0x58, 0xe7, 0x1b, 0x81, 0x81, 0xbc, 0x74, 0x61, 0x93, 0x0b, 0x92, 0x0d, 0xa2, 0xd4, 0xff, 0x1c,
	0x5a, 0x6f, 0xd3, 0x38, 0x4f, 0xc8, 0xab, 0x34, 0xa7, 0xe5, 0xdc, 0x41, 0x50, 0x57, 0xb5, 0xd6,
	0xd4, 0x51, 0xdf, 0xbe, 0x0f, 0x6d, 0xad, 0x76, 0xa9, 0xe3, 0x2c, 0x4b, 0xd9, 0x2b, 0x70, 0x34,
	0xa6, 0xd4, 0xea, 0xe1, 0x42, 0xc6, 0x5a, 0xfd, 0x87, 0x05, 0x87, 0x8b, 0xa6, 0x6d, 0x2a, 0xfd,
	0x77, 0x55, 0xd8, 0x3a, 0x4d, 0xa9, 0xc0, 0x11, 0x25, 0xec, 0x32, 0x23, 0xa1, 0x24, 0x75, 0x94,
	0xe0, 0xb1, 0xb5, 0xab, 0x05, 0xe4, 0xc1, 0x66, 0x98, 0x26, 0x09, 0xa6, 0x43, 0xaf, 0xba, 0x57,
	0xdb, 0x77, 0x03, 0x2b, 0xa2, 0x27, 0x50, 0x23, 0x74, 0xe2, 0xd5, 0xf6, 0x6a, 0xfb, 0xad, 0xfe,
	0x87, 0x85, 0xf7, 0x16, 0xcc, 0xf6, 0xce, 0xe8, 0xe4, 0x8c, 0x0a, 0x36, 0x0d, 0x24, 0x1a, 0x9d,
	0x81, 0xcb, 0x88, 0x76, 0x81, 0x7b, 0x8e, 0x52, 0xfd, 0x78, 0xad, 0x6a, 0x60, 0x91, 0xda, 0xc0,
	0x5c, 0x13, 0x7d, 0x05, 0x5b, 0x13, 0x15, 0xd5, 0x20, 0x91, 0x89, 0xe6, 0xde, 0xa6, 0x32, 0xb5,
	0xbb, 0x12, 0xb5, 0xaa, 0x43, 0xd0, 0x9e, 0xcc, 0x05, 0xde, 0xfd, 0x02, 0x9a, 0xd6, 0x29, 0x3b,
	0x12, 0x2a, 0x25, 0x23, 0xa1, 0xd8, 0xdb, 0x5f, 0x56, 0x9f, 0x57, 0xba, 0x2f, 0xa0, 0xb3, 0xe8,
	0xd1, 0x5d, 0xb4, 0xfd, 0x3f, 0x2a, 0xd0, 0xb6, 0xea, 0x2a, 0xdf, 0x5d, 0x68, 0x26, 0x98, 0x46,
	0x23, 0xc2, 0x85, 0xb1, 0x30, 0x93, 0xd1, 0x01, 0xec, 0xf0, 0x5c, 0xf7, 0x7d, 0x98, 0xd2, 0x61,
	0x24, 0xa2, 0x94, 0x1a, 0x93, 0xdb, 0xe6, 0xe2, 0xd4, 0x9e, 0x4b, 0xf0, 0x08, 0x47, 0x71, 0xce,
	0x48, 0x01, 0xac, 0x87, 0xd0, 0xb6, 0xb9, 0x98, 0x83, 0x77, 0xc1, 0xc1, 0xa1, 0x42, 0xe8, 0x61,
	0x64, 0x24, 0xd4, 0x83, 0xfb, 0x9c, 0x88, 0x41, 0x7a, 0x4b, 0x09, 0x1b, 0x30, 0x32, 0x22, 0x8c,
	0xd0, 0x90, 0x28, 0xfa, 0x37, 0x83, 0x1d, 0x4e, 0xc4, 0x85, 0xbc, 0x09, 0xec, 0x85, 0xff, 0xae,
	0x02, 0x9d, 0x53, 0x4c, 0x29, 0x19, 0xca, 0x3e, 0x56, 0x01, 0x95, 0xf1, 0xf2, 0x19, 0xd4, 0x31,
	0x1b, 0x73, 0xc5, 0x9d, 0x56, 0xff, 0xa3, 0x62, 0xa9, 0x17, 0x94, 0x7b, 0x27, 0x6c, 0x6c, 0xca,
	0xac, 0x14, 0xd0, 0x27, 0xe0, 0x44, 0x34, 0xcb, 0x05, 0x37, 0x04, 0x5b, 0xec, 0x40, 0x39, 0x39,
	0x02, 0x03, 0x40, 0x07, 0xb0, 0x99, 0xe6, 0x42, 0x61, 0xeb, 0xeb, 0xb0, 0x16, 0xd1, 0x7d, 0x06,
	0xee, 0xec, 0xa9, 0x3b, 0xd5, 0xef, 0xaf, 0x3a, 0xd4, 0xa5, 0x31, 0xd4, 0x81, 0x6a, 0x34, 0x54,
	0x3a, 0x8d, 0xa0, 0x1a, 0x0d, 0x67, 0x61, 0x57, 0x0b, 0x61, 0xff, 0x0f, 0x5c, 0x91, 0x64, 0x0b,
	0x6b, 0xaa, 0x29, 0x0f, 0xe4, 0x68, 0x44, 0xdf, 0x40, 0x27, 0xb4, 0x3c, 0x1f, 0xf0, 0x8c, 0x84,
	0x66, 0x2a, 0x79, 0xeb, 0x1a, 0x21, 0xd8, 0x0a, 0x17, 0x3a, 0xf5, 0x05, 0x6c, 0xd9, 0x56, 0xd0,
	0xfa, 0x8d, 0x95, 0x9e, 0x2f, 0x32, 0x2d, 0x68, 0xb3, 0x22, 0xef, 0x4e, 0x61, 0x3b, 0x54, 0xb9,
	0x1f, 0xa8, 0xa9, 0xa5, 0x0c, 0xe8, 0xc5, 0xf2, 0x68, 0x6d, 0x79, 0x82, 0x4e, 0xb8, 0x58, 0x6b,
	0x39, 0xa1, 0x43, 0x16, 0x65, 0x42, 0x6d, 0x18, 0x37, 0x30, 0x12, 0x7a, 0x6c, 0xea, 0xdd, 0x5c,
	0x57, 0x08, 0x5d, 0x5d, 0x1f, 0xda, 0x43, 0x92, 0x11, 0x3a, 0x24, 0x34, 0x8c, 0x08, 0xf7, 0x5c,
	0x35, 0x5a, 0x16, 0xce, 0x64, 0x5e, 0x6f, 0xaf, 0x09, 0x35, 0xbb, 0x45, 0x7d, 0xa3, 0x23, 0x68,
	0x60, 0x21, 0x18, 0xf7, 0x5a, 0xca, 0x7e, 0x77, 0xc9, 0x7e, 0xef, 0x44, 0x5e, 0x6a, 0x1a, 0x69,
	0xa0, 0x24, 0x87, 0xde, 0x74, 0xdc, 0x6b, 0xaf, 0xfa, 0xa4, 0x77, 0xa1, 0x45, 0x48, 0xb0, 0x9e,
	0x14, 0xdc, 0xdb, 0x5a, 0x01, 0xeb, 0x81, 0x12, 0x58, 0x44, 0xf7, 0x35, 0xc0, 0xfc, 0xb9, 0x12,
	0x2a, 0x7d, 0x5a, 0xa4, 0x92, 0x5c, 0x54, 0xfa, 0x77, 0xa8, 0x67, 0x7f, 0x87, 0x7a, 0x27, 0x74,
	0x5a, 0x24, 0xd8, 0x73, 0xb8, 0x77, 0x9a, 0xd2, 0x30, 0x67, 0x8c, 0x50, 0x21, 0xa3, 0xe1, 0xe8,
	0x31, 0x34, 0x64, 0x8d, 0xb8, 0x57, 0x51, 0xde, 0xdc, 0x5b, 0x0a, 0x37, 0xd0, 0xb7, 0xfe, 0x6f,
	0xd0, 0x96, 0xe2, 0x8f, 0x24, 0xc9, 0x62, 0x2c, 0xca, 0x17, 0xc4, 0xbc, 0x9f, 0xaa, 0x77, 0xe8,
	0xa7, 0xda, 0xbf, 0xf5, 0x93, 0xff, 0x77, 0x0d, 0x9a, 0x3f, 0xa7, 0xec, 0x66, 0x14, 0xa7, 0xb7,
	0xa5, 0x0f, 0x1f, 0xd9, 0x18, 0xaa, 0x2b, 0x25, 0x5b, 0x0a, 0xd7, 0x84, 0x83, 0xbe, 0x05, 0x57,
	0x98, 0x50, 0xac, 0x07, 0x7e, 0x41, 0xcb, 0xbe, 0xd6, 0xb3, 0xf1, 0xda, 0xf5, 0x30, 0x53, 0x42,
	0x7b, 0xd0, 0x92, 0xeb, 0x3f, 0x8e, 0x49, 0x1c, 0xf1, 0x44, 0xb5, 0x57, 0x23, 0x28, 0x1e, 0x29,
	0xfe, 0xaa, 0xa2, 0x9b, 0x7f, 0x2e, 0x23, 0xa1, 0xaf, 0x01, 0x91, 0x5f, 0x23, 0x31, 0xb8, 0xc6,
	0x74, 0x18, 0xcb, 0xf6, 0x54, 0xae, 0x3b, 0xe5, 0xe9, 0xdf, 0x96, 0xd0, 0x73, 0x8d, 0xd4, 0x05,
	0x7b, 0x6a, 0xf9, 0xa9, 0xf7, 0xd1, 0xfb, 0x65, 0x6e, 0xaf, 0x70, 0xb4, 0xfb, 0x13, 0x74, 0x16,
	0x63, 0x29, 0x61, 0xd3, 0x67, 0x8b, 0x6c, 0x7a, 0xb8, 0xe4, 0x8b, 0xd5, 0x2f, 0xee, 0xab, 0xff,
	0x98, 0xa0, 0x2f, 0x5b, 0xbf, 0x98, 0x9f, 0xfb, 0xc3, 0xc9, 0xf1, 0x95, 0xa3, 0x50, 0x4f, 0xfe,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xc9, 0xf0, 0x3c, 0xfe, 0x0b, 0x00, 0x00,
}
