repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    - id: insert-license
      name: Add license for all python files
      exclude: ^(\.github|examples)/.*$
      types: [python]
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - templates/LICENSE.txt
        - --fuzzy-match-generates-todo
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args: [--line-length=79]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
  - id: go-fmt
  - id: go-lint 
  - id: no-go-testing

exclude: 'couler/proto/*'
