// Code generated by protoc-gen-go. DO NOT EDIT.
// source: step_zoo.proto

package couler_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SingleContainerStep struct {
	Image                string              `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command              string              `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Env                  map[string]*any.Any `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources            *TaskSpec           `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SingleContainerStep) Reset()         { *m = SingleContainerStep{} }
func (m *SingleContainerStep) String() string { return proto.CompactTextString(m) }
func (*SingleContainerStep) ProtoMessage()    {}
func (*SingleContainerStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{0}
}

func (m *SingleContainerStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleContainerStep.Unmarshal(m, b)
}
func (m *SingleContainerStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleContainerStep.Marshal(b, m, deterministic)
}
func (m *SingleContainerStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleContainerStep.Merge(m, src)
}
func (m *SingleContainerStep) XXX_Size() int {
	return xxx_messageInfo_SingleContainerStep.Size(m)
}
func (m *SingleContainerStep) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleContainerStep.DiscardUnknown(m)
}

var xxx_messageInfo_SingleContainerStep proto.InternalMessageInfo

func (m *SingleContainerStep) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SingleContainerStep) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *SingleContainerStep) GetEnv() map[string]*any.Any {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *SingleContainerStep) GetResources() *TaskSpec {
	if m != nil {
		return m.Resources
	}
	return nil
}

type TaskSpec struct {
	Count                int32                   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Image                string                  `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command              string                  `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	ContainerResources   *ContainerResourcesSpec `protobuf:"bytes,4,opt,name=container_resources,json=containerResources,proto3" json:"container_resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TaskSpec) Reset()         { *m = TaskSpec{} }
func (m *TaskSpec) String() string { return proto.CompactTextString(m) }
func (*TaskSpec) ProtoMessage()    {}
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{1}
}

func (m *TaskSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskSpec.Unmarshal(m, b)
}
func (m *TaskSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskSpec.Marshal(b, m, deterministic)
}
func (m *TaskSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskSpec.Merge(m, src)
}
func (m *TaskSpec) XXX_Size() int {
	return xxx_messageInfo_TaskSpec.Size(m)
}
func (m *TaskSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TaskSpec proto.InternalMessageInfo

func (m *TaskSpec) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TaskSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *TaskSpec) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *TaskSpec) GetContainerResources() *ContainerResourcesSpec {
	if m != nil {
		return m.ContainerResources
	}
	return nil
}

type ContainerResourcesSpec struct {
	Cpu                  float32  `protobuf:"fixed32,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               int32    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk                 int32    `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Gpu                  int32    `protobuf:"varint,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerResourcesSpec) Reset()         { *m = ContainerResourcesSpec{} }
func (m *ContainerResourcesSpec) String() string { return proto.CompactTextString(m) }
func (*ContainerResourcesSpec) ProtoMessage()    {}
func (*ContainerResourcesSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{2}
}

func (m *ContainerResourcesSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerResourcesSpec.Unmarshal(m, b)
}
func (m *ContainerResourcesSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerResourcesSpec.Marshal(b, m, deterministic)
}
func (m *ContainerResourcesSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerResourcesSpec.Merge(m, src)
}
func (m *ContainerResourcesSpec) XXX_Size() int {
	return xxx_messageInfo_ContainerResourcesSpec.Size(m)
}
func (m *ContainerResourcesSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerResourcesSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerResourcesSpec proto.InternalMessageInfo

func (m *ContainerResourcesSpec) GetCpu() float32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ContainerResourcesSpec) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *ContainerResourcesSpec) GetDisk() int32 {
	if m != nil {
		return m.Disk
	}
	return 0
}

func (m *ContainerResourcesSpec) GetGpu() int32 {
	if m != nil {
		return m.Gpu
	}
	return 0
}

type DistributedStep struct {
	Runtime              string               `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	TaskGroups           map[string]*TaskSpec `protobuf:"bytes,2,rep,name=task_groups,json=taskGroups,proto3" json:"task_groups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RuntimeArgs          map[string]string    `protobuf:"bytes,3,rep,name=runtime_args,json=runtimeArgs,proto3" json:"runtime_args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DistributedStep) Reset()         { *m = DistributedStep{} }
func (m *DistributedStep) String() string { return proto.CompactTextString(m) }
func (*DistributedStep) ProtoMessage()    {}
func (*DistributedStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{3}
}

func (m *DistributedStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributedStep.Unmarshal(m, b)
}
func (m *DistributedStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributedStep.Marshal(b, m, deterministic)
}
func (m *DistributedStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributedStep.Merge(m, src)
}
func (m *DistributedStep) XXX_Size() int {
	return xxx_messageInfo_DistributedStep.Size(m)
}
func (m *DistributedStep) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributedStep.DiscardUnknown(m)
}

var xxx_messageInfo_DistributedStep proto.InternalMessageInfo

func (m *DistributedStep) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *DistributedStep) GetTaskGroups() map[string]*TaskSpec {
	if m != nil {
		return m.TaskGroups
	}
	return nil
}

func (m *DistributedStep) GetRuntimeArgs() map[string]string {
	if m != nil {
		return m.RuntimeArgs
	}
	return nil
}

type OdpsSqlStep struct {
	SqlScript            string   `protobuf:"bytes,1,opt,name=sql_script,json=sqlScript,proto3" json:"sql_script,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OdpsSqlStep) Reset()         { *m = OdpsSqlStep{} }
func (m *OdpsSqlStep) String() string { return proto.CompactTextString(m) }
func (*OdpsSqlStep) ProtoMessage()    {}
func (*OdpsSqlStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{4}
}

func (m *OdpsSqlStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OdpsSqlStep.Unmarshal(m, b)
}
func (m *OdpsSqlStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OdpsSqlStep.Marshal(b, m, deterministic)
}
func (m *OdpsSqlStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OdpsSqlStep.Merge(m, src)
}
func (m *OdpsSqlStep) XXX_Size() int {
	return xxx_messageInfo_OdpsSqlStep.Size(m)
}
func (m *OdpsSqlStep) XXX_DiscardUnknown() {
	xxx_messageInfo_OdpsSqlStep.DiscardUnknown(m)
}

var xxx_messageInfo_OdpsSqlStep proto.InternalMessageInfo

func (m *OdpsSqlStep) GetSqlScript() string {
	if m != nil {
		return m.SqlScript
	}
	return ""
}

func (m *OdpsSqlStep) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *OdpsSqlStep) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type OdpsPaiStep struct {
	CodeName             string            `protobuf:"bytes,1,opt,name=code_name,json=codeName,proto3" json:"code_name,omitempty"`
	Params               map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OdpsPaiStep) Reset()         { *m = OdpsPaiStep{} }
func (m *OdpsPaiStep) String() string { return proto.CompactTextString(m) }
func (*OdpsPaiStep) ProtoMessage()    {}
func (*OdpsPaiStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{5}
}

func (m *OdpsPaiStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OdpsPaiStep.Unmarshal(m, b)
}
func (m *OdpsPaiStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OdpsPaiStep.Marshal(b, m, deterministic)
}
func (m *OdpsPaiStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OdpsPaiStep.Merge(m, src)
}
func (m *OdpsPaiStep) XXX_Size() int {
	return xxx_messageInfo_OdpsPaiStep.Size(m)
}
func (m *OdpsPaiStep) XXX_DiscardUnknown() {
	xxx_messageInfo_OdpsPaiStep.DiscardUnknown(m)
}

var xxx_messageInfo_OdpsPaiStep proto.InternalMessageInfo

func (m *OdpsPaiStep) GetCodeName() string {
	if m != nil {
		return m.CodeName
	}
	return ""
}

func (m *OdpsPaiStep) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type OdpsMRStep struct {
	LibJars              string   `protobuf:"bytes,1,opt,name=lib_jars,json=libJars,proto3" json:"lib_jars,omitempty"`
	MainClass            string   `protobuf:"bytes,2,opt,name=main_class,json=mainClass,proto3" json:"main_class,omitempty"`
	JvmProperties        string   `protobuf:"bytes,3,opt,name=jvm_properties,json=jvmProperties,proto3" json:"jvm_properties,omitempty"`
	Args                 string   `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OdpsMRStep) Reset()         { *m = OdpsMRStep{} }
func (m *OdpsMRStep) String() string { return proto.CompactTextString(m) }
func (*OdpsMRStep) ProtoMessage()    {}
func (*OdpsMRStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{6}
}

func (m *OdpsMRStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OdpsMRStep.Unmarshal(m, b)
}
func (m *OdpsMRStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OdpsMRStep.Marshal(b, m, deterministic)
}
func (m *OdpsMRStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OdpsMRStep.Merge(m, src)
}
func (m *OdpsMRStep) XXX_Size() int {
	return xxx_messageInfo_OdpsMRStep.Size(m)
}
func (m *OdpsMRStep) XXX_DiscardUnknown() {
	xxx_messageInfo_OdpsMRStep.DiscardUnknown(m)
}

var xxx_messageInfo_OdpsMRStep proto.InternalMessageInfo

func (m *OdpsMRStep) GetLibJars() string {
	if m != nil {
		return m.LibJars
	}
	return ""
}

func (m *OdpsMRStep) GetMainClass() string {
	if m != nil {
		return m.MainClass
	}
	return ""
}

func (m *OdpsMRStep) GetJvmProperties() string {
	if m != nil {
		return m.JvmProperties
	}
	return ""
}

func (m *OdpsMRStep) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type OdpsSparkStep struct {
	SparkVersion         string   `protobuf:"bytes,1,opt,name=spark_version,json=sparkVersion,proto3" json:"spark_version,omitempty"`
	LibJars              string   `protobuf:"bytes,2,opt,name=lib_jars,json=libJars,proto3" json:"lib_jars,omitempty"`
	MainClass            string   `protobuf:"bytes,3,opt,name=main_class,json=mainClass,proto3" json:"main_class,omitempty"`
	SparkConf            string   `protobuf:"bytes,4,opt,name=spark_conf,json=sparkConf,proto3" json:"spark_conf,omitempty"`
	Args                 string   `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OdpsSparkStep) Reset()         { *m = OdpsSparkStep{} }
func (m *OdpsSparkStep) String() string { return proto.CompactTextString(m) }
func (*OdpsSparkStep) ProtoMessage()    {}
func (*OdpsSparkStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{7}
}

func (m *OdpsSparkStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OdpsSparkStep.Unmarshal(m, b)
}
func (m *OdpsSparkStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OdpsSparkStep.Marshal(b, m, deterministic)
}
func (m *OdpsSparkStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OdpsSparkStep.Merge(m, src)
}
func (m *OdpsSparkStep) XXX_Size() int {
	return xxx_messageInfo_OdpsSparkStep.Size(m)
}
func (m *OdpsSparkStep) XXX_DiscardUnknown() {
	xxx_messageInfo_OdpsSparkStep.DiscardUnknown(m)
}

var xxx_messageInfo_OdpsSparkStep proto.InternalMessageInfo

func (m *OdpsSparkStep) GetSparkVersion() string {
	if m != nil {
		return m.SparkVersion
	}
	return ""
}

func (m *OdpsSparkStep) GetLibJars() string {
	if m != nil {
		return m.LibJars
	}
	return ""
}

func (m *OdpsSparkStep) GetMainClass() string {
	if m != nil {
		return m.MainClass
	}
	return ""
}

func (m *OdpsSparkStep) GetSparkConf() string {
	if m != nil {
		return m.SparkConf
	}
	return ""
}

func (m *OdpsSparkStep) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type CustomStep struct {
	Manifest             string   `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	SuccessCondition     string   `protobuf:"bytes,2,opt,name=success_condition,json=successCondition,proto3" json:"success_condition,omitempty"`
	FailureCondition     string   `protobuf:"bytes,3,opt,name=failure_condition,json=failureCondition,proto3" json:"failure_condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomStep) Reset()         { *m = CustomStep{} }
func (m *CustomStep) String() string { return proto.CompactTextString(m) }
func (*CustomStep) ProtoMessage()    {}
func (*CustomStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{8}
}

func (m *CustomStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomStep.Unmarshal(m, b)
}
func (m *CustomStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomStep.Marshal(b, m, deterministic)
}
func (m *CustomStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomStep.Merge(m, src)
}
func (m *CustomStep) XXX_Size() int {
	return xxx_messageInfo_CustomStep.Size(m)
}
func (m *CustomStep) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomStep.DiscardUnknown(m)
}

var xxx_messageInfo_CustomStep proto.InternalMessageInfo

func (m *CustomStep) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *CustomStep) GetSuccessCondition() string {
	if m != nil {
		return m.SuccessCondition
	}
	return ""
}

func (m *CustomStep) GetFailureCondition() string {
	if m != nil {
		return m.FailureCondition
	}
	return ""
}

type CannedStep struct {
	Inputs               []*StepIO            `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*StepIO            `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	SingleContainerStep  *SingleContainerStep `protobuf:"bytes,3,opt,name=single_container_step,json=singleContainerStep,proto3" json:"single_container_step,omitempty"`
	DistributedStep      *DistributedStep     `protobuf:"bytes,4,opt,name=distributed_step,json=distributedStep,proto3" json:"distributed_step,omitempty"`
	OdpsSqlStep          *OdpsSqlStep         `protobuf:"bytes,5,opt,name=odps_sql_step,json=odpsSqlStep,proto3" json:"odps_sql_step,omitempty"`
	OdpsPaiStep          *OdpsPaiStep         `protobuf:"bytes,6,opt,name=odps_pai_step,json=odpsPaiStep,proto3" json:"odps_pai_step,omitempty"`
	OdpsMrStep           *OdpsMRStep          `protobuf:"bytes,7,opt,name=odps_mr_step,json=odpsMrStep,proto3" json:"odps_mr_step,omitempty"`
	OdpsSparkStep        *OdpsSparkStep       `protobuf:"bytes,8,opt,name=odps_spark_step,json=odpsSparkStep,proto3" json:"odps_spark_step,omitempty"`
	CustomStep           *CustomStep          `protobuf:"bytes,9,opt,name=custom_step,json=customStep,proto3" json:"custom_step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CannedStep) Reset()         { *m = CannedStep{} }
func (m *CannedStep) String() string { return proto.CompactTextString(m) }
func (*CannedStep) ProtoMessage()    {}
func (*CannedStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_a44d094245c913e3, []int{9}
}

func (m *CannedStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CannedStep.Unmarshal(m, b)
}
func (m *CannedStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CannedStep.Marshal(b, m, deterministic)
}
func (m *CannedStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CannedStep.Merge(m, src)
}
func (m *CannedStep) XXX_Size() int {
	return xxx_messageInfo_CannedStep.Size(m)
}
func (m *CannedStep) XXX_DiscardUnknown() {
	xxx_messageInfo_CannedStep.DiscardUnknown(m)
}

var xxx_messageInfo_CannedStep proto.InternalMessageInfo

func (m *CannedStep) GetInputs() []*StepIO {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *CannedStep) GetOutputs() []*StepIO {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *CannedStep) GetSingleContainerStep() *SingleContainerStep {
	if m != nil {
		return m.SingleContainerStep
	}
	return nil
}

func (m *CannedStep) GetDistributedStep() *DistributedStep {
	if m != nil {
		return m.DistributedStep
	}
	return nil
}

func (m *CannedStep) GetOdpsSqlStep() *OdpsSqlStep {
	if m != nil {
		return m.OdpsSqlStep
	}
	return nil
}

func (m *CannedStep) GetOdpsPaiStep() *OdpsPaiStep {
	if m != nil {
		return m.OdpsPaiStep
	}
	return nil
}

func (m *CannedStep) GetOdpsMrStep() *OdpsMRStep {
	if m != nil {
		return m.OdpsMrStep
	}
	return nil
}

func (m *CannedStep) GetOdpsSparkStep() *OdpsSparkStep {
	if m != nil {
		return m.OdpsSparkStep
	}
	return nil
}

func (m *CannedStep) GetCustomStep() *CustomStep {
	if m != nil {
		return m.CustomStep
	}
	return nil
}

func init() {
	proto.RegisterType((*SingleContainerStep)(nil), "couler.v1.SingleContainerStep")
	proto.RegisterMapType((map[string]*any.Any)(nil), "couler.v1.SingleContainerStep.EnvEntry")
	proto.RegisterType((*TaskSpec)(nil), "couler.v1.TaskSpec")
	proto.RegisterType((*ContainerResourcesSpec)(nil), "couler.v1.ContainerResourcesSpec")
	proto.RegisterType((*DistributedStep)(nil), "couler.v1.DistributedStep")
	proto.RegisterMapType((map[string]string)(nil), "couler.v1.DistributedStep.RuntimeArgsEntry")
	proto.RegisterMapType((map[string]*TaskSpec)(nil), "couler.v1.DistributedStep.TaskGroupsEntry")
	proto.RegisterType((*OdpsSqlStep)(nil), "couler.v1.OdpsSqlStep")
	proto.RegisterType((*OdpsPaiStep)(nil), "couler.v1.OdpsPaiStep")
	proto.RegisterMapType((map[string]string)(nil), "couler.v1.OdpsPaiStep.ParamsEntry")
	proto.RegisterType((*OdpsMRStep)(nil), "couler.v1.OdpsMRStep")
	proto.RegisterType((*OdpsSparkStep)(nil), "couler.v1.OdpsSparkStep")
	proto.RegisterType((*CustomStep)(nil), "couler.v1.CustomStep")
	proto.RegisterType((*CannedStep)(nil), "couler.v1.CannedStep")
}

func init() { proto.RegisterFile("step_zoo.proto", fileDescriptor_a44d094245c913e3) }

var fileDescriptor_a44d094245c913e3 = []byte{
	// 941 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0x87, 0xed, 0xd8, 0xb1, 0x4f, 0x49, 0xe3, 0x2a, 0x69, 0xe0, 0x7a, 0xd8, 0x90, 0x79, 0x18,
	0x96, 0x36, 0x80, 0x8b, 0x66, 0xc0, 0xb6, 0xe6, 0x61, 0x58, 0xe1, 0x05, 0xc3, 0xfe, 0xb4, 0x0d,
	0xe8, 0x61, 0x0f, 0x7b, 0x11, 0x68, 0x89, 0xf6, 0x18, 0x4b, 0xa4, 0x42, 0x52, 0x06, 0xbc, 0xb7,
	0xee, 0x9b, 0x0c, 0xd8, 0xd3, 0x3e, 0xd3, 0x3e, 0xcc, 0xc0, 0x23, 0x65, 0x2b, 0x8e, 0x13, 0xa0,
	0x6f, 0xbc, 0xd3, 0xdd, 0x4f, 0xbf, 0xbb, 0xfb, 0x1d, 0x09, 0x8f, 0xb4, 0x61, 0x79, 0xf4, 0xa7,
	0x94, 0xc3, 0x5c, 0x49, 0x23, 0xc3, 0x4e, 0x2c, 0x8b, 0x94, 0xa9, 0xe1, 0xe2, 0x65, 0x7f, 0xcf,
	0x1f, 0xf1, 0x43, 0xff, 0xe9, 0x4c, 0xca, 0x59, 0xca, 0x5e, 0xa0, 0x35, 0x29, 0xa6, 0x2f, 0xa8,
	0x58, 0xba, 0x4f, 0x83, 0xf7, 0x75, 0x38, 0x1c, 0x73, 0x31, 0x4b, 0xd9, 0x48, 0x0a, 0x43, 0xb9,
	0x60, 0x6a, 0x6c, 0x58, 0x1e, 0x1e, 0x41, 0x93, 0x67, 0x74, 0xc6, 0x7a, 0xb5, 0x93, 0xda, 0x69,
	0x87, 0x38, 0x23, 0xec, 0xc1, 0x6e, 0x2c, 0xb3, 0x8c, 0x8a, 0xa4, 0x57, 0x47, 0x7f, 0x69, 0x86,
	0xaf, 0xa0, 0xc1, 0xc4, 0xa2, 0xd7, 0x38, 0x69, 0x9c, 0x06, 0xe7, 0x5f, 0x0c, 0x57, 0x4c, 0x86,
	0x5b, 0xc0, 0x87, 0x97, 0x62, 0x71, 0x29, 0x8c, 0x5a, 0x12, 0x9b, 0x13, 0xbe, 0x84, 0x8e, 0x62,
	0x5a, 0x16, 0x2a, 0x66, 0xba, 0xb7, 0x73, 0x52, 0x3b, 0x0d, 0xce, 0x0f, 0x2b, 0x00, 0xbf, 0x52,
	0x3d, 0x1f, 0xe7, 0x2c, 0x26, 0xeb, 0xa8, 0xfe, 0x2f, 0xd0, 0x2e, 0x31, 0xc2, 0x2e, 0x34, 0xe6,
	0x6c, 0xe9, 0x79, 0xda, 0x63, 0xf8, 0x1c, 0x9a, 0x0b, 0x9a, 0x16, 0x0c, 0x39, 0x06, 0xe7, 0x47,
	0x43, 0x57, 0xfe, 0xb0, 0x2c, 0x7f, 0xf8, 0x5a, 0x2c, 0x89, 0x0b, 0xb9, 0xa8, 0x7f, 0x53, 0x1b,
	0xfc, 0x53, 0x83, 0x76, 0xf9, 0x17, 0x5b, 0x78, 0x2c, 0x0b, 0x61, 0x10, 0xb0, 0x49, 0x9c, 0xb1,
	0x6e, 0x47, 0xfd, 0x9e, 0x76, 0x34, 0x6e, 0xb7, 0x83, 0xc0, 0x61, 0x5c, 0x96, 0x1c, 0x6d, 0x56,
	0xf7, 0x69, 0xa5, 0xba, 0x55, 0x63, 0x48, 0x19, 0x84, 0xb5, 0x86, 0xf1, 0x1d, 0xff, 0xe0, 0x0f,
	0x38, 0xde, 0x1e, 0x6d, 0x5b, 0x10, 0xe7, 0x05, 0x32, 0xae, 0x13, 0x7b, 0x0c, 0x8f, 0xa1, 0x95,
	0xb1, 0x4c, 0xaa, 0x25, 0x12, 0x6e, 0x12, 0x6f, 0x85, 0x21, 0xec, 0x24, 0x5c, 0xcf, 0x91, 0x6e,
	0x93, 0xe0, 0xd9, 0x66, 0xcf, 0xf2, 0x02, 0xb9, 0x35, 0x89, 0x3d, 0x0e, 0xfe, 0xab, 0xc3, 0xc1,
	0xf7, 0x5c, 0x1b, 0xc5, 0x27, 0x85, 0x61, 0x09, 0x0a, 0xa2, 0x07, 0xbb, 0xaa, 0x10, 0x86, 0x67,
	0xa5, 0x24, 0x4a, 0x33, 0xfc, 0x19, 0x02, 0x43, 0xf5, 0x3c, 0x9a, 0x29, 0x59, 0xe4, 0xba, 0x57,
	0x47, 0x09, 0x3c, 0xaf, 0xd4, 0xb8, 0x01, 0x85, 0x13, 0xfd, 0x01, 0x83, 0x9d, 0x0a, 0xc0, 0xac,
	0x1c, 0xe1, 0x5b, 0xd8, 0xf3, 0xb8, 0x11, 0x55, 0x33, 0xed, 0x05, 0x75, 0xf6, 0x00, 0x1a, 0x71,
	0xe1, 0xaf, 0xd5, 0xcc, 0xc3, 0x05, 0x6a, 0xed, 0xe9, 0x13, 0x38, 0xd8, 0xf8, 0xdd, 0x16, 0xc1,
	0x3c, 0xbb, 0x2d, 0x98, 0xad, 0xea, 0x5b, 0xeb, 0xa5, 0xff, 0x2d, 0x74, 0x37, 0x7f, 0xba, 0x05,
	0xf4, 0xa8, 0x0a, 0xda, 0xa9, 0xea, 0xed, 0x77, 0x08, 0xde, 0x25, 0xb9, 0x1e, 0xdf, 0xa4, 0xd8,
	0xd9, 0x8f, 0x01, 0xf4, 0x4d, 0x1a, 0xe9, 0x58, 0xf1, 0xdc, 0x78, 0x84, 0x8e, 0xbe, 0x49, 0xc7,
	0xe8, 0xb0, 0x23, 0xcb, 0x64, 0x52, 0xc2, 0xe0, 0xd9, 0x0e, 0x23, 0x57, 0xf2, 0x9a, 0xc5, 0xa6,
	0x14, 0x9e, 0x37, 0x07, 0x7f, 0xd7, 0x1c, 0xf8, 0x15, 0xe5, 0x08, 0xfe, 0x11, 0x74, 0x62, 0x99,
	0xb0, 0x48, 0xd0, 0xd5, 0xe0, 0xda, 0xd6, 0xf1, 0x96, 0x66, 0x2c, 0xbc, 0x80, 0x56, 0x4e, 0x15,
	0xcd, 0xca, 0xa1, 0x0d, 0x2a, 0x85, 0x57, 0x40, 0x86, 0x57, 0x18, 0xe4, 0xba, 0xeb, 0x33, 0xfa,
	0xaf, 0x20, 0xa8, 0xb8, 0x3f, 0xa8, 0xfe, 0xf7, 0x35, 0x00, 0x0b, 0xff, 0x86, 0x20, 0xc5, 0xa7,
	0xd0, 0x4e, 0xf9, 0x24, 0xba, 0xa6, 0x4a, 0x97, 0xd2, 0x4a, 0xf9, 0xe4, 0x27, 0xaa, 0xb4, 0x6d,
	0x4d, 0x46, 0xb9, 0x88, 0xe2, 0x94, 0x6a, 0xed, 0x81, 0x3a, 0xd6, 0x33, 0xb2, 0x8e, 0xf0, 0x73,
	0x78, 0x74, 0xbd, 0xc8, 0xa2, 0x5c, 0xc9, 0x9c, 0x29, 0xc3, 0x99, 0xf6, 0xdd, 0xd8, 0xbf, 0x5e,
	0x64, 0x57, 0x2b, 0xa7, 0xed, 0x20, 0x6a, 0x69, 0xc7, 0x75, 0xd0, 0x9e, 0x6d, 0x9f, 0xf6, 0x71,
	0x08, 0x39, 0x55, 0x73, 0xa4, 0xf1, 0x19, 0xec, 0x6b, 0x6b, 0x44, 0x0b, 0xa6, 0x34, 0x97, 0xc2,
	0x73, 0xd9, 0x43, 0xe7, 0x6f, 0xce, 0x77, 0x8b, 0x6b, 0xfd, 0x21, 0xae, 0x8d, 0x4d, 0xae, 0x76,
	0xca, 0x08, 0x1f, 0x4b, 0x31, 0xf5, 0x54, 0x3a, 0xe8, 0x19, 0x49, 0x31, 0x5d, 0x71, 0x6c, 0x56,
	0x38, 0xfe, 0x55, 0x03, 0x18, 0x15, 0xda, 0xc8, 0x0c, 0x09, 0xf6, 0xa1, 0x9d, 0x51, 0xc1, 0xa7,
	0x4c, 0x97, 0x2a, 0x59, 0xd9, 0xe1, 0x19, 0x3c, 0xd6, 0x45, 0x1c, 0x33, 0xad, 0x2d, 0x7e, 0xc2,
	0x8d, 0x2d, 0xc0, 0x11, 0xec, 0xfa, 0x0f, 0xa3, 0xd2, 0x6f, 0x83, 0xa7, 0x94, 0xa7, 0x85, 0x62,
	0x95, 0x60, 0x47, 0xb8, 0xeb, 0x3f, 0xac, 0x82, 0x07, 0xff, 0xee, 0x00, 0x8c, 0xa8, 0x10, 0xfe,
	0x1a, 0x78, 0x06, 0x2d, 0x2e, 0xf2, 0xc2, 0xd8, 0x51, 0x59, 0xc9, 0x3c, 0xae, 0x5e, 0xf5, 0x86,
	0xe5, 0x3f, 0xbe, 0x23, 0x3e, 0x20, 0x3c, 0x83, 0x5d, 0x59, 0x18, 0x8c, 0xad, 0xdf, 0x17, 0x5b,
	0x46, 0x84, 0x04, 0x9e, 0x68, 0x7c, 0x29, 0xa2, 0xf5, 0xbd, 0x69, 0x9f, 0x37, 0xe4, 0x15, 0x9c,
	0x7f, 0xf2, 0xf0, 0x8b, 0x42, 0x0e, 0xf5, 0x96, 0x37, 0xec, 0x12, 0xba, 0xc9, 0xfa, 0xb2, 0x70,
	0x70, 0xee, 0x06, 0xee, 0xdf, 0x7f, 0x9f, 0x90, 0x83, 0x64, 0xe3, 0xe6, 0xbb, 0x80, 0x7d, 0x99,
	0xe4, 0x3a, 0xc2, 0x25, 0xb5, 0x18, 0x4d, 0xc4, 0x38, 0xde, 0x58, 0x16, 0xbf, 0xce, 0x24, 0x90,
	0x95, 0xdd, 0x2e, 0x73, 0x73, 0xca, 0x5d, 0x6e, 0x6b, 0x6b, 0xae, 0x5f, 0x34, 0x97, 0x5b, 0xae,
	0xee, 0xd7, 0xb0, 0x87, 0xb9, 0x99, 0xef, 0xc4, 0x2e, 0xa6, 0x3e, 0xd9, 0x48, 0x75, 0x4b, 0x44,
	0xc0, 0x86, 0xbe, 0x71, 0x75, 0x7f, 0x07, 0x07, 0x8e, 0x30, 0xea, 0x0d, 0x73, 0xdb, 0x98, 0xdb,
	0xdb, 0xa4, 0x5c, 0x8a, 0x9f, 0x20, 0xcb, 0xf5, 0x2e, 0x7c, 0x05, 0x41, 0x8c, 0xc2, 0x73, 0xd9,
	0x9d, 0x3b, 0x7f, 0x5e, 0xcb, 0x92, 0x40, 0xbc, 0x3a, 0x4f, 0x5a, 0xf8, 0xc4, 0x7e, 0xf9, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x3a, 0x68, 0xbf, 0x9a, 0x08, 0x00, 0x00,
}
