name: docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.7
      - run: python -m pip install -r requirements.txt -r requirements-dev.txt
      - run: mkdocs gh-deploy --force
